apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack

type: application

version: 0.1.0

appVersion: "v0.87.0"

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 80.9.1
