elasticsearch:
  replicas: 3
  minimumMasterNodes: 2
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=30s"
  updateStrategy: OnDelete

  secret:
    enabled: false

  readinessProbe:
    timeoutSeconds: 35

  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  esJavaOpts: "-Xmx1g -Xms1g"

  persistence:
    enabled: true
    size: "10Gi"

  antiAffinity: "soft"
