metallb:
  controller:
    enabled: true
    image:
      pullPolicy: Always
  # rbac:
  #   create: false
  # prometheus:
  #   serviceAccount: "kube-prometheus-stack-prometheus"
  #   namespace: "observability"
  #   serviceMonitor:
  #     enabled: true