kubecost:
  global:
    clusterId: "cluster-one"
    # prometheus:
    #   enabled: true
    #   fqdn: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
    #   insecureSkipVerify: true
    # grafana:
    #   enabled: false
    #   domainName: http://kube-prometheus-grafana.observability.svc.cluster.local:80