apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openspeedtest-ingress
  namespace: openspeedtest
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`speedtest.shivpatel.xyz`)
      kind: Rule
      services:
        - name: openspeedtest
          port: 3000
  tls: {}
