apiVersion: v2
appVersion: v0.4.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.38
description: A Helm chart for LibreChat
home: https://www.librechat.ai
name: librechat-rag-api
type: application
version: 0.5.2
