apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-home-ingress
  namespace: adguard-home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.shivpatel.xyz`)
      kind: Rule
      services:
        - name: adguard-home
          port: 80
  tls: {}
