apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingress
  namespace: keycloak
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`keycloak.shivpatel.xyz`)
    kind: Rule
    services:
    - name: keycloak
      port: 8080
  tls: {}