apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opencost-ingress
  namespace: opencost
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`opencost.shivpatel.xyz`)
      kind: Rule
      services:
        - name: opencost
          port: 9090
  tls: {}
