apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: observability
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`prometheus.shivpatel.xyz`)
    kind: Rule
    services:
    - name: prometheus-host
      port: 9090