apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-ingress
  namespace: headlamp
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`headlamp.shivpatel.xyz`)
    kind: Rule
    services:
    - name: headlamp
      port: 80
  tls: {}