apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingress
  namespace: immich
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`immich.shivpatel.xyz`)
    kind: Rule
    services:
    - name: immich
      port: 80
  tls: {}