apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-db-config
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-db-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        database: |
          USER = {{ .username }}
          PASSWD = {{ .password }}
  dataFrom:
    - extract:
        key: secret/data/postgresql/gitea
