apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-db-config
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-db-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        database: |
          USER = {{ .DB_USER }}
          PASSWD = {{ .DB_PASSWORD }}
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/postgresql/gitea
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/postgresql/gitea
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/data/redis
        property: redis-password
