apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kafka-ui-ingress
  namespace: kafka
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kafka.shivpatel.xyz`)
      kind: Rule
      services:
        - name: kafka-ui
          port: 80
  tls: {}
