policy-reporter:
  plugin:
    kyverno:
      enabled: true
  ui:
    enabled: true
  podAnnotations:
    ad.datadoghq.com/policy-reporter.checks: |
      {
        "kyverno": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8000/metrics"
            }
          ]
        }
      }
  monitoring:
    enabled: true
