apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: outline-ingress
  namespace: outline
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`outline.shivpatel.xyz`)
      kind: Rule
      services:
        - name: outline
          port: 3000
  tls: {}
