apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - cert-managerv
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.shivpatel.xyz"
    - "shivpatel.xyz"
  ipAddresses:
    - 192.168.86.10
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer