k8s-monitoring:
  cluster:
    name: homelab

  destinations:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.observability.svc.cluster.local:80/api/v1/write
    - name: loki
      type: loki
      url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

  alloy-metrics:
    enabled: true
  alloy-singleton:
    enabled: true
  clusterMetrics:
    enabled: true
  clusterEvents:
    enabled: true