apiVersion: v2
name: traefik
description: A Helm chart for Traefik

type: application

version: 0.1.0

appVersion: "v3.5.3"

dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 39.0.1
