apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubeview-ingress
  namespace: kubeview
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kubeview.shivpatel.xyz`)
      kind: Rule
      services:
        - name: kubeview
          port: 8000
  tls: {}
