apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ingress
  namespace: pgadmin4
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`pgadmin.shivpatel.xyz`)
    kind: Rule
    services:
    - name: pgadmin4
      port: 80
  tls: {}