apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postgresql-ingress
  namespace: postgresql
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`postgresql.shivpatel.xyz`)
    kind: Rule
    services:
    - name: postgresql
      port: 80
  tls: {}