apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy-ingress
  namespace: observability
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`alloy.shivpatel.xyz`)
    kind: Rule
    services:
    - name: alloy
      port: 12345
  tls: {}