apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-ingress
  namespace: lnextcloud
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`nextcloud.shivpatel.xyz`)
    kind: Rule
    services:
    - name: nextcloud
      port: 80
  tls: {}