apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingress
  namespace: harbor
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`harbor.shivpatel.xyz`)
    kind: Rule
    services:
    - name: harbor-portal
      port: 80
  tls: {}