apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`home.shivpatel.xyz`)
    kind: Rule
    services:
    - name: home-assistant
      port: 8080
  tls: {}