pihole:
  admin:
    enabled: true
    existingSecret: "pihole-custom-password"
    passwordKey: "password"
  replicaCount: 1
  strategyType: Recreate
  persistentVolumeClaim:
    enabled: true

  serviceWeb:
    loadBalancerIP: 192.168.20.21
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  serviceDns:
    loadBalancerIP: 192.168.20.21
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer
