apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools-ingress
  namespace: it-tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tools.shivpatel.xyz`)
      kind: Rule
      services:
        - name: it-tools
          port: 8080
  tls: {}
