apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql-rw-ingress
  namespace: postgresql
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`postgresql-rw.shivpatel.xyz`)
      services:
        - name: postgresql-rw
          port: 5432
  tls:
    passthrough: true
