apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teslamate-ingress
  namespace: teslamate
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tesla.shivpatel.xyz`)
      kind: Rule
      services:
        - name: teslamate
          port: 4000
  tls: {}
