apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mongodb-ingress
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mongodb.shivpatel.xyz`)
      kind: Rule
      services:
        - name: mongodb
          port: 27017
  tls: {}
