apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cloudnative-pg-ingress
  namespace: cloudnative-pg
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`cloudnative-pg.shivpatel.xyz`)
    kind: Rule
    services:
    - name: cloudnative-pg
      port: 3000
  tls: {}