minio:
  mode: distributed
  statefulset:
    replicaCount: 3
    drivesPerNode: 2
    updateStrategy:
      type: OnDelete
  auth:
    existingSecret: "minio-root-credentials"
    rootUserSecretKey: "root-user"
    rootPasswordSecretKey: "root-password"
  image:
    registry: docker.io
    repository: bitnamilegacy/minio
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
  console:
    image:
      registry: docker.io
      repository: bitnamilegacy/minio-object-browser
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
