apiVersion: v2
name: grafana
description: A Helm chart for Grafana

type: application

version: 0.1.0

appVersion: "12.2.0"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 10.1.0
