apiVersion: v2
name: prometheus
description: A Helm chart for Prometheus

type: application

version: 0.1.0

appVersion: "v3.6.0"

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 27.50.1
