apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pyroscope-ingress
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pyroscope.shivpatel.xyz`)
      kind: Rule
      services:
        - name: pyroscope
          port: 4040
  tls: {}
