apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shivppatel/k8s.git
    targetRevision: main
    path: apps/homer
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: homer
