apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-ingress
  namespace: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitlab.shivpatel.xyz`)
      kind: Rule
      services:
        - name: gitlab-webservice-default
          port: 8181
  tls: {}
