apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-kas-ingress
  namespace: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kas.shivpatel.xyz`) && PathPrefix(`/k8s-proxy/`)
      kind: Rule
      services:
        - name: gitlab-kas
          port: 8154
    - match: Host(`kas.shivpatel.xyz`)
      kind: Rule
      services:
        - name: gitlab-kas
          port: 8150
  tls: {}
